language: node_js
node_js:
  - 6
install:
  - npm install
  - npm run typings
notifications:
  email:
    - carriere.denis@gmail.com
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
